### ISSUE TITLE
command 'projectQ.addCategory' not found

### ISSUE THREAD

**Issue by alexluoli** [QuincyX/vscode-extension-projectQ#1]
vscode版本: 1.39.2
提交: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
日期: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Comment by QuincyX** [comment]
抱歉暂时没做mac平台兼容

**Comment by QuincyX** [comment]
因为本人不用mac，也没想到vscode on mac用户这么多，借此招募一个小伙伴帮忙调试下mac下的兼容性，或者直接提个pr
大概只要修改下这个方法就可以了
 ~/srv/util/index getFilePathFromAppData

**Comment by QuincyX** [comment]
V0.1.7 已修复
